import React from 'react';
import type { Metadata } from "next";
import "@/app/styles/globals.css";
import {Quicksand} from "next/font/google";
import Shared from "@/app/Shared";
import {deviceBreakpoint} from "@/app/styles/device-query";
import ComingSoon from "@/app/coming-soon/ComingSoon";

// const rouge_script = Rouge_Script({ weight: "400" });
const quicksand = Quicksand();

export const metadata: Metadata = {
    title: "TechKun",
    description: "Generated by create next app",
};

export default function RootLayout() {
    return (
        <html lang="en" style={{
            "--mobile-s": `${deviceBreakpoint.mobileS}px`,
            "--mobile-m": `${deviceBreakpoint.mobileM}px`,
            "--mobile-l": `${deviceBreakpoint.mobileL}px`,
            "--tablet": `${deviceBreakpoint.tablet}px`,
            "--laptop": `${deviceBreakpoint.laptop}px`,
            "--laptop-l": `${deviceBreakpoint.laptopL}px`,
            "--desktop": `${deviceBreakpoint.desktop}px`
        } as React.CSSProperties}>
            <body>
                <Shared />
                <ComingSoon/>
            </body>
        </html>
    );
}
